----CREATE DATABASE DATABASEADI 

----CREATE TABLE TABLOADI 
----(
----KOLON1 VERÝ TÝPÝ ,
----KOLON2 VERÝ TÝPÝ ,
----.
----..
----.
----.
----)

----USE model
----GO
----CREATE TABLE TEST
----(
----NAME VARCHAR(100)

----)


----CREATE DATABASE SILIKONAKADEMI

----CREATE DATABASE TEST1

----DROP TABLE TEST

----DROP DATABASE SILIKONAKADEMI
----DROP DATABASE TEST1

----CREATE DATABASE SILIKONAKDEMI


----USE [SILIKONAKDEMI]
----GO 
----CREATE TABLE PERSONEL
----(
----TC CHAR(11),
----AD VARCHAR(10),
----SOYAD VARCHAR(10),
----)





--CHAR()  --1 BYTE VERÝ TUTARMMAX 8000
--VARCHAR() --1 BYTE VERÝ TUTAR MAX 8000


--CREATE TABLE TEST

--(
--TC CHAR(10)
--NAME VARCHAR(10)


--)
----METÝNSEL VERÝ TÝPLER
--CHAR
--VARCHAR

----SAYISAL VERÝ TÝPLER

----ÝNT :4 BYTE ALAN KAPLAR -2MÝLYAR ÝLE +2 MÝLYAR ARASINDA VERÝ SETÝ TUTAR
----SMALLÝNT: 2 BYTE ALAN KAPLAR -32000+32000 ARALIÐINDA VERÝ SETÝ TUTAR.


--SELECT * FROM PERSONEL

----INSERT INTO PERSONEL(TC,AD,SOYAD) VALUES ('1234432112','ANIL','KALKAN')
----INSERT INTO PERSONEL(TC,AD,SOYAD) VALUES ('6727327348','Mert','ÖzYardýmcý')
----INSERT INTO PERSONEL (TC,AD,SOYAD) VALUES('6723456234','Beþir','Velioðlu')
----INSERT INTO PERSONEL(TC,AD,SOYAD) VALUES ('2322322','ANL','KLKN')
----INSERT INTO PERSONEL(TC,AD,SOYAD) VALUES ('2322322','ANIL','KLKN')
----GO 100

----SELECT * FROM PERSONEL

----SELECT * INTO PERSONEL_ESKITC FROM PERSONEL WHERE TC= '2322322'   




----UPDATE(TABLO ÜZERÝNDEKÝ KAYITLARIN DEÐÝÞTÝRÝLMESÝNÝ SAÐLAYAN KOMUT)

----UPDATE PERSONEL SET AD='BEYZA' WHERE AD='ANIL'
----SELECT * FROM PERSONEL



----BEGIN TRAN
----UPDATE PERSONEL SET AD='HALUK'

SELECT * FROM PERSONEL

ALTER TABLE PERSONEL 
ADD MAAS INT


SELECT * FROM PERSONEL

UPDATE PERSONEL SET MAAS=100

SELECT * FROM PERSONEL

UPDATE PERSONEL SET MAAS=MAAS+100 WHERE AD='ANIL'

SELECT * FROM PERSONEL


--DELETE (TABLO ÝÇERÝSÝNDEKÝ VERÝLERÝ SÝLMEK ÝÇÝN KULLANILAN KOMUT)


--SELECT * FROM PERSONEL

---- PERSONEL TABLOSUNDA SOYAD BÝLGÝSÝ ÖzYardýmcý OLAN KAYITLARI SÝL
--DELETE FROM PERSONEL WHERE SOYAD='ÖzYardýmcý' AND AD=

--TRUNCATE TABLE PERSONEL_ESKI

--SELECT * FROM PERSONEL_ESKI


--CREATE DATABASE SQLSERVER

--CREATE TABLE OGRENCILER
--(
--OGRNO INT,
--AD VARCHAR(100),
--SOYAD VARCHAR(100),
--OKUL VARCHAR(100)
--)

--SELECT * FROM OGRENCILER

--INSERT INTO OGRENCILER VALUES (1,'ALÝ','DURU','AKDENÝZ UNÝ')
--INSERT INTO OGRENCILER(AD,SOYAD,OKUL) VALUES ('FATÝH','KALKAN','SÝNOP UNÝ')
--INSERT INTO OGRENCILER VALUES('AHMET','KAYMAZ','EGE UNÝ')

--INSERT INTO OGRENCILER VALUES(2,'HARUN','AÇIK','MARMARA UNI')

--UPDATE OGRENCILER SET OGRNO=3 WHERE AD='FATÝH'

--SELECT * FROM OGRENCILER ORDER BY OGRNO DESC

--INSERT INTO OGRENCILER VALUES(23,'ZEYNEP','AKSU','DENÝZLÝ UNÝ')
--GO 100


--DELETE FROM OGRENCILER WHERE OGRNO=23

SELECT * FROM PERSONEL

CREATE TABLE [AN.AD]

(
ID INT,
NAME VARCHAR(10)

)

SELECT * FROM  AN.AD






















