SQL SERVER’DA METÝNSEL,SAYISAL VE TARÝHSEL VERÝ TÝPLERÝNÝ VE AÇIKLAMLARINI YAZINIZ.


—SQL SERVER ÜZERÝNDE BÝR DATAKOD ADINDA BÝR DATABASE OLUÞTURUNUZ

—OLUÞTURULAN BU DATABASE ALTINDA PERSONEL ADINDA BÝR TABLO OLUÞTURUNUZ.

—PERSONEL TABLOSU ALTINDA AD,SOYAD VE DOGUMTARIHI ADINDA 3 KOLON OUSTURUNUZ.

—BU TABLOYA 10 INSERT ISLEMI YAPINIZ.
